USE [master]
GO
/****** Object:  Database [AdminPanel]    Script Date: 1/12/2020 6:27:44 PM ******/
CREATE DATABASE [AdminPanel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdminPanel', FILENAME = N'E:\DB\AdminPanel.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdminPanel_log', FILENAME = N'E:\DB\AdminPanel_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AdminPanel] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdminPanel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AdminPanel] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AdminPanel] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AdminPanel] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AdminPanel] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AdminPanel] SET ARITHABORT OFF 
GO
ALTER DATABASE [AdminPanel] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AdminPanel] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AdminPanel] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AdminPanel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AdminPanel] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AdminPanel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AdminPanel] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AdminPanel] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AdminPanel] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AdminPanel] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AdminPanel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AdminPanel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AdminPanel] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AdminPanel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AdminPanel] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AdminPanel] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AdminPanel] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AdminPanel] SET RECOVERY FULL 
GO
ALTER DATABASE [AdminPanel] SET  MULTI_USER 
GO
ALTER DATABASE [AdminPanel] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AdminPanel] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AdminPanel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AdminPanel] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AdminPanel] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AdminPanel', N'ON'
GO
ALTER DATABASE [AdminPanel] SET QUERY_STORE = OFF
GO
USE [AdminPanel]
GO
/****** Object:  Table [dbo].[Education]    Script Date: 1/12/2020 6:27:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Education](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ProfileId] [bigint] NOT NULL,
	[DegreeTitle] [nvarchar](max) NULL,
	[School] [nvarchar](max) NULL,
	[PassingYear] [nvarchar](max) NULL,
	[TotalMarks] [int] NULL,
	[MarksObtained] [int] NULL,
	[Percentage] [int] NULL,
	[isActive] [bit] NULL,
	[isDeleted] [bit] NULL,
 CONSTRAINT [PK_Education] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Log]    Script Date: 1/12/2020 6:27:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Log](
	[Date] [datetime] NOT NULL,
	[Thread] [nvarchar](50) NULL,
	[Level] [nvarchar](50) NULL,
	[Logger] [nvarchar](50) NULL,
	[Message] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profile]    Script Date: 1/12/2020 6:27:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profile](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](max) NULL,
	[FatherName] [nvarchar](max) NULL,
	[NIC] [nvarchar](max) NULL,
	[Address] [nvarchar](max) NULL,
	[Gender] [nchar](10) NULL,
	[Email] [nvarchar](max) NULL,
	[MobileNumber] [bigint] NULL,
	[isDeleted] [bit] NULL,
 CONSTRAINT [PK_Profile] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 1/12/2020 6:27:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Email] [nchar](50) NOT NULL,
	[Password] [nchar](15) NULL,
	[isActive] [bit] NOT NULL,
	[isDeleted] [bit] NOT NULL,
	[isVerified] [bit] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [AdminPanel] SET  READ_WRITE 
GO
